import CancelApprovalConfirmModal from "./CancelApprovalConfirm/CancelApprovalConfirmModal";
import CancelPendingConfirmModal from "./CancelPendingConfirm/CancelPendingConfirmModal";
import FileApplicationModal from "./FileApplicationModal";
import HrNoteConfirmModal from "./HrNoteConfirm/HrNoteConfirmModal";
import LeaveConfirmationModal from "./LeaveConfirmation/LeaveConfirmationModal";
import PendingApprovalModal from "./PendingApproval/PendingApprovalModal";
import MyPendingRequestsModal from "./PendingRequest/MyPendingRequestModal";
import ReviewConfirmationModal from "./ReviewConfirmation/ReviewConfirmationModal";

export default function ModalsContainer({
  applicationModalOpen,
  currentUser,
  setApplicationModalOpen,
  applicationType,
  setApplicationType,
  formError,
  handleFromDateChange,
  handleLeaveTypeChange,
  handleToDateChange,
  getMaxToDate,
  formData,
  setFormData,
  availableLeaveTypes,
  difference,
  handleSubmitLeave,
  resignationForm,
  setResignationForm,
  resignationTypes,
  fileResignationMutation,
  pendingModalOpen,
  isApprover,
  setPendingModalOpen,
  pendingTypeFilter,
  setPendingTypeFilter,
  allPendingRequests,
  pendingLeaveApprovals,
  pendingOffsetApprovals,
  pendingResignationApprovals,
  filteredPendingRequests,
  isHRRole,
  canHrDirectDecision,
  isPendingApprovalStatus,
  openResignationDecisionConfirm,
  openLeaveDecisionConfirm,
  openOffsetDecisionConfirm,
  setHrNoteConfirm,
  myPendingModalOpen,
  setMyPendingModalOpen,
  myRequestRows,
  cancelMyPendingRequestMutation,
  setCancelPendingConfirm,
  requestCancellationApprovalMutation,
  setCancelApprovalConfirm,
  confirmAction,
  setConfirmAction,
  fileOffsetMutation,
  submitLeaveMutation,
  reviewConfirm,
  setReviewConfirm,
  getDateRangeInclusive,
  toggleLeaveApprovedDate,
  parseDateOnly,
  getOffsetRequestedDays,
  submitReviewDecision,
  cancelApprovalConfirm,
  cancelPendingConfirm,
  hrNoteConfirm,
  addHrNoteMutation,
  reviewResignationMutation,
  showToast,
  submitCancellationRequest,
}) {
  return (
    <>
      <FileApplicationModal
        applicationModalOpen={applicationModalOpen}
        currentUser={currentUser}
        setApplicationModalOpen={setApplicationModalOpen}
        applicationType={applicationType}
        setApplicationType={setApplicationType}
        formError={formError}
        handleFromDateChange={handleFromDateChange}
        handleLeaveTypeChange={handleLeaveTypeChange}
        handleToDateChange={handleToDateChange}
        getMaxToDate={getMaxToDate}
        formData={formData}
        setFormData={setFormData}
        availableLeaveTypes={availableLeaveTypes}
        difference={difference}
        handleSubmitLeave={handleSubmitLeave}
        resignationForm={resignationForm}
        setResignationForm={setResignationForm}
        resignationTypes={resignationTypes}
        fileResignationMutation={fileResignationMutation}
      />
      <PendingApprovalModal
        pendingModalOpen={pendingModalOpen}
        isApprover={isApprover}
        setPendingModalOpen={setPendingModalOpen}
        pendingTypeFilter={pendingTypeFilter}
        setPendingTypeFilter={setPendingTypeFilter}
        allPendingRequests={allPendingRequests}
        pendingLeaveApprovals={pendingLeaveApprovals}
        pendingOffsetApprovals={pendingOffsetApprovals}
        pendingResignationApprovals={pendingResignationApprovals}
        filteredPendingRequests={filteredPendingRequests}
        isHRRole={isHRRole}
        canHrDirectDecision={canHrDirectDecision}
        isPendingApprovalStatus={isPendingApprovalStatus}
        openResignationDecisionConfirm={openResignationDecisionConfirm}
        openLeaveDecisionConfirm={openLeaveDecisionConfirm}
        openOffsetDecisionConfirm={openOffsetDecisionConfirm}
        setHrNoteConfirm={setHrNoteConfirm}
        reviewResignationMutation={reviewResignationMutation}
        showToast={showToast}
      />
      <MyPendingRequestsModal
        myPendingModalOpen={myPendingModalOpen}
        setMyPendingModalOpen={setMyPendingModalOpen}
        myRequestRows={myRequestRows}
        cancelMyPendingRequestMutation={cancelMyPendingRequestMutation}
        setCancelPendingConfirm={setCancelPendingConfirm}
        requestCancellationApprovalMutation={
          requestCancellationApprovalMutation
        }
        setCancelApprovalConfirm={setCancelApprovalConfirm}
      />
      <LeaveConfirmationModal
        confirmAction={confirmAction}
        setConfirmAction={setConfirmAction}
        fileOffsetMutation={fileOffsetMutation}
        submitLeaveMutation={submitLeaveMutation}
        formData={formData}
      />
      <ReviewConfirmationModal
        reviewConfirm={reviewConfirm}
        setReviewConfirm={setReviewConfirm}
        getDateRangeInclusive={getDateRangeInclusive}
        toggleLeaveApprovedDate={toggleLeaveApprovedDate}
        parseDateOnly={parseDateOnly}
        getOffsetRequestedDays={getOffsetRequestedDays}
        submitReviewDecision={submitReviewDecision}
      />
      <CancelApprovalConfirmModal
        cancelApprovalConfirm={cancelApprovalConfirm}
        setCancelApprovalConfirm={setCancelApprovalConfirm}
        requestCancellationApprovalMutation={
          requestCancellationApprovalMutation
        }
        submitCancellationRequest={submitCancellationRequest}
      />
      <CancelPendingConfirmModal
        cancelPendingConfirm={cancelPendingConfirm}
        setCancelPendingConfirm={setCancelPendingConfirm}
        cancelMyPendingRequestMutation={cancelMyPendingRequestMutation}
      />
      <HrNoteConfirmModal
        hrNoteConfirm={hrNoteConfirm}
        setHrNoteConfirm={setHrNoteConfirm}
        addHrNoteMutation={addHrNoteMutation}
        showToast={showToast}
      />
    </>
  );
}
